from setuptools import setup, find_packages

setup(
    name="open-insect",
    version="1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "torch>=1.31.1",
        "torchvision>=0.13",
        "scikit-learn",
        "json5",
        "matplotlib",
        "scipy",
        "tqdm",
        "pyyaml>=5.4.1",
        "pre-commit",
        "opencv-python>=4.4.0.46",
        "imgaug>=0.4.0",
        "pandas",
        "diffdist>=0.1",
        "Cython>=0.29.30",
        "faiss-gpu>=1.7.2",
        "gdown>=4.7.1",
        "wandb",
        "numpy==1.26.4",
        "timm",
    ],
    author="anonymous",
    description="Package for the Open-Insect benchmark",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: Debian based Linux",
    ],
)
