network:
  name: resnet50
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False         
  
  checkpoint: ./checkpoints/resnet50-0676ba61.pth           
  num_gpus: '@{num_gpus}'

  # this field will not be used but for an unified interface
  backbone:
    name: resnet50

