dataset:
  name: ami_c-america
  num_classes: 636
  num_closed_set: 636
  pre_size: 128
  image_size: 126

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized_new/
    imglist_pth:  /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_train_id.txt
    csv_path: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/03_c-america_train_id.csv 
    json_path: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/03_ami-gbif_fine-grained_c-america_category_map.json
    batch_size: 128
    shuffle: True
    len: 72188
  val:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized_new/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_val_id.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized_new/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_test_id.txt
    batch_size: 128
    shuffle: False

    