ood_dataset:
  name: ami_c-america_ood
  num_classes: 10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [osr]
  
  osr:
    datasets: [osr]
    osr:
      data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
      imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_val_ood.txt


