dataset:
  name: open-insect-example
  num_classes: 636
  num_closed_set: 636
  pre_size: 224 # the original size of the image
  image_size: 126 # the size of the image as the input to the model

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./example/images
    imglist_pth: ./example/metadata/train_id.txt # the metadata (a txt file with the following format:<image path> <label>)
    batch_size: 512
    shuffle: True
    json_path: ./metadata/c-america_id_class_distribution.json 
    len: 636 # total number of images
  val:
    dataset_class: ImglistDataset
    data_dir: ./example/images # the image directory 
    imglist_pth: ./example/metadata/val_id.txt # the metadata (a txt file with the following format:<image path> <label>)
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./example/images # the image directory 
    imglist_pth: ./example/metadata/test_id.txt # the metadata (a txt file with the following format:<image path> <label>)
    batch_size: 128
    shuffle: False
  
  