dataset:
  name: open-insect-example-ood-oe
  split_names: [train, oe, val, test]
  oe:
    dataset_class: ImglistDataset
    data_dir: ./images
    imglist_pth: ./example/metadata/train_aux.txt
    batch_size: 512
    shuffle: True
    interpolation: bilinear
